/*=============================================================================
  Copyright (C) 2015-2016 DxLibEx project
  https://github.com/Nagarei/DxLibEx/

  Distributed under the Boost Software License, Version 1.0.
  (See http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/
#ifndef WIN32_REG_INC_CONFIG_SUFFIX_HPP_
#define WIN32_REG_INC_CONFIG_SUFFIX_HPP_

#include "no_min_max.h"
#include "compiler.hpp"
//
// WIN32_REG_CONSTEXPR
// WIN32_REG_CONSTEXPR_OR_CONST
// WIN32_REG_STATIC_CONSTEXPR
// WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_INNER
// WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_OUTER
//
#ifndef WIN32_REG_NO_CXX11_CONSTEXPR
#	define WIN32_REG_CONSTEXPR constexpr
#	define WIN32_REG_CONSTEXPR_OR_CONST constexpr
#	define WIN32_REG_STATIC_CONSTEXPR static constexpr
#
#	define WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_INNER(EXPR) = EXPR
#	define WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_OUTER(EXPR)
#else	// #ifndef WIN32_REG_NO_CXX11_CONSTEXPR
#	define WIN32_REG_CONSTEXPR
#	define WIN32_REG_CONSTEXPR_OR_CONST const
#	define WIN32_REG_STATIC_CONSTEXPR static const
#
#	define WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_INNER(EXPR)
#	define WIN32_REG_STATIC_CONSTEXPR_DATA_MEMBER_OUTER(EXPR) = EXPR
#endif	// #ifndef WIN32_REG_NO_CXX11_CONSTEXPR

//
// WIN32_REG_CXX14_CONSTEXPR
// WIN32_REG_CXX14_CONSTEXPR_OR_CONST
// WIN32_REG_CXX14_STATIC_CONSTEXPR
//
#ifndef WIN32_REG_NO_CXX14_CONSTEXPR
#	define WIN32_REG_CXX14_CONSTEXPR WIN32_REG_CONSTEXPR
#	define WIN32_REG_CXX14_CONSTEXPR_OR_CONST WIN32_REG_CONSTEXPR_OR_CONST
#	define WIN32_REG_CXX14_STATIC_CONSTEXPR WIN32_REG_STATIC_CONSTEXPR
#else	// #ifndef WIN32_REG_NO_CXX14_CONSTEXPR
#	define WIN32_REG_CXX14_CONSTEXPR
#	define WIN32_REG_CXX14_CONSTEXPR_OR_CONST const
#	define WIN32_REG_CXX14_STATIC_CONSTEXPR static const
#	ifndef WIN32_REG_NO_CXX11_CONSTEXPR
#		define WIN32_REG_SUPPORT_ONLY_CXX11_CONSTEXPR
#	endif
#endif	// #ifndef WIN32_REG_NO_CXX14_CONSTEXPR

//
// WIN32_REG_INITIALIZER_LIST_CONSTEXPR
//
#ifndef WIN32_REG_NO_CXX14_INITIALIZER_LIST
#	define WIN32_REG_INITIALIZER_LIST_CONSTEXPR WIN32_REG_CXX14_CONSTEXPR
#else	// #ifndef WIN32_REG_NO_CXX14_INITIALIZER_LIST
#	define WIN32_REG_INITIALIZER_LIST_CONSTEXPR
#endif	// #ifndef WIN32_REG_NO_CXX14_INITIALIZER_LIST


//
// WIN32_REG_DEPRECATED
//
#if defined(__GNUC__) || defined(__clang__)
#	define WIN32_REG_DEPRECATED __attribute__((deprecated))
#elif defined(_MSC_VER)
#	define WIN32_REG_DEPRECATED __declspec(deprecated)
#else
#	define WIN32_REG_DEPRECATED
#endif

//
// WIN32_REG_NOEXCEPT
// WIN32_REG_NOEXCEPT_OR_NOTHROW
//
#ifndef WIN32_REG_NO_CXX11_NOEXCEPT
#	define WIN32_REG_NOEXCEPT noexcept
#	define WIN32_REG_NOEXCEPT_OR_NOTHROW noexcept
#else	// #ifndef WIN32_REG_CONFIG_DISABLE_NOEXCEPT
#	define WIN32_REG_NOEXCEPT
#	define WIN32_REG_NOEXCEPT_OR_NOTHROW throw()
#endif	// #ifndef WIN32_REG_CONFIG_DISABLE_NOEXCEPT

//
// WIN32_REG_NOEXCEPT_IF
// WIN32_REG_NOEXCEPT_EXPR
// WIN32_REG_NOEXCEPT_EXPR_OR_DEFAULT
// WIN32_REG_NOEXCEPT_IF_EXPR
//
#ifndef WIN32_REG_NO_CXX11_NOEXCEPT_EXPRESSION
#	define WIN32_REG_NOEXCEPT_IF(COND) noexcept((COND))
#	define WIN32_REG_NOEXCEPT_EXPR(EXPR) noexcept((EXPR))
#	define WIN32_REG_NOEXCEPT_EXPR_OR_DEFAULT(EXPR, C) noexcept((EXPR))
#	define WIN32_REG_NOEXCEPT_IF_EXPR(EXPR) noexcept(noexcept((EXPR)))
#else //WIN32_REG_NO_CXX11_NOEXCEPT_EXPRESSION
#	define WIN32_REG_NOEXCEPT_IF(COND)
#	define WIN32_REG_NOEXCEPT_EXPR(EXPR) false
#	define WIN32_REG_NOEXCEPT_EXPR_OR_DEFAULT(EXPR, C) C
#	define WIN32_REG_NOEXCEPT_IF_EXPR(EXPR)
#endif //WIN32_REG_NO_CXX11_NOEXCEPT_EXPRESSION

//
// WIN32_REG_USE_UNICODE_LITERALS
//
#ifndef WIN32_REG_NO_CXX11_UNICODE_LITERALS
#	define WIN32_REG_USE_UNICODE_LITERALS 1
#else	// #ifndef WIN32_REG_CONFIG_DISABLE_UNICODE_LITERALS
#	define WIN32_REG_USE_UNICODE_LITERALS 0
#endif	// #ifndef WIN32_REG_CONFIG_DISABLE_UNICODE_LITERALS

//
// WIN32_REG_REF_QUALIFIERS_LVALUE
// WIN32_REG_REF_QUALIFIERS_RVALUE
//
#ifndef WIN32_REG_NO_CXX11_REF_QUALIFIERS
#	define WIN32_REG_REF_QUALIFIERS_LVALUE &
#	define WIN32_REG_REF_QUALIFIERS_RVALUE &&
#else
#	define WIN32_REG_REF_QUALIFIERS_LVALUE
#	define WIN32_REG_REF_QUALIFIERS_RVALUE
#endif

//
// WIN32_REG_PREVENT_MACRO_SUBSTITUTION
//
#define WIN32_REG_PREVENT_MACRO_SUBSTITUTION

#endif	// #ifndef WIN32_REG_INC_CONFIG_SUFFIX_HPP_
